// export const Typography = {
// 	fontFamily: ["Inter/sans-serif"],
// 	fontWeightRegular: "400",
// 	fontWeightMedium: "500",
// 	fontWeightSemibold: "600",
// 	fontWeightBold: "700",
// 	heading: {
// 		fontFamily: this.fontFamily,
// 		fontWeight: this.fontWeightBold,
// 		fontSize: "22px",
// 		lineHeight: "26",
// 		letterSpacing: "-0.5",
// 	},
// 	name: {
// 		fontFamily: this.fontFamily,
// 		fontWeight: this.fontWeightMedium,
// 		fontSize: "16px",
// 		lineHeight: "18",
// 		letterSpacing: "-0.1",
// 	},
// 	Title1: {
// 		fontFamily: this.fontFamily,
// 		fontWeight: this.fontWeightSemibold,
// 		fontSize: "15px",
// 		lineHeight: "22",
// 		letterSpacing: "-0.1",
// 	},
// 	Title2: {
// 		fontFamily: this.fontFamily,
// 		fontWeight: this.fontWeightRegular,
// 		fontSize: "22px",
// 		lineHeight: "22",
// 		letterSpacing: "-0.1",
// 	},
// 	Subtitle1: {
// 		fontFamily: this.fontFamily,
// 		fontWeight: this.fontWeightRegular,
// 		fontSize: "15px",
// 		lineHeight: "22",
// 		letterSpacing: "-0.1",
// 	},
// 	Subtitle2: {
// 		fontFamily: this.fontFamily,
// 		fontWeight: this.fontWeightRegular,
// 		fontSize: "13px",
// 		lineHeight: "18, 20",
// 		letterSpacing: "-0.1",
// 	},
// 	Text1: {
// 		fontFamily: this.fontFamily,
// 		fontWeight: this.fontWeightMedium,
// 		fontSize: "15px",
// 		lineHeight: "18, 22",
// 		letterSpacing: "-0.1",
// 	},
// 	Text2: {
// 		fontFamily: this.fontFamily,
// 		fontWeight: this.fontWeightMedium,
// 		fontSize: "13px",
// 		lineHeight: "18",
// 		letterSpacing: "-0.1",
// 	},
// 	Caption1: {
// 		fontFamily: this.fontFamily,
// 		fontWeight: this.fontWeightMedium,
// 		fontSize: "12px",
// 		lineHeight: "16",
// 		letterSpacing: "-0.1",
// 	},
// 	Caption2: {
// 		fontFamily: this.fontFamily,
// 		fontWeight: this.fontWeightMedium,
// 		fontSize: "11px",
// 		lineHeight: "12",
// 		letterSpacing: "-0.1",
// 	},
// };